-- ============================================================================
-- EMI Dashboard — Complete Schema (AWS-Portable, All-in-One)
-- ============================================================================
-- Purpose:     Single-file deployment DDL for a fresh Postgres instance.
--              Consolidates migrations 01-15 + inline KAN-35/36/47 additions.
-- Target:      AWS RDS Postgres 13+ (also works on any Postgres 13+ install)
-- Author:      DK Nguyen + Claude (Trustify Technology) for Huy Nguyen Duc
-- Date:        2026-04-21
-- Version:     v1.0 — initial AWS migration candidate
--
-- ── What this file INCLUDES ─────────────────────────────────────────────────
--   1. ENUMs (ticket_status, ticket_scenario, ticket_risk_level, ticket_type)
--   2. Core tables (tickets_v2, ticket_emails, ticket_attachments,
--      ticket_vision_results, ticket_employee_extractions, activity_log)
--   3. All KAN-35/36/47 column additions baked INLINE (no later ALTER)
--   4. Auto-update triggers (updated_at, ticket_number generator)
--   5. Indexes for dashboard query performance
--   6. tickets_flat read-side view (dashboard's primary query surface)
--   7. Smoke-test verification block at bottom (commented — run after deploy)
--
-- ── What this file DOES NOT INCLUDE (intentional, separate concerns) ────────
--   ✗ pg_net / pg_cron mechanisms (Supabase-only, not available on AWS RDS)
--   ✗ email_queue table + triggers (coupled to pg_net; replace with EventBridge
--     or Lambda on AWS — see MIGRATION-NOTES section at bottom of this file)
--   ✗ Supabase RLS policies using auth.uid() (not portable to AWS; replace
--     with IAM / Cognito / app-level auth later)
--   ✗ Supabase Storage bucket policies (AWS deployment uses S3 instead;
--     storage_url column stores the S3 key or path, schema unchanged)
--   ✗ Seed data (this is pure DDL — insert test rows via the smoke-test block)
--
-- ── How to deploy on AWS RDS ────────────────────────────────────────────────
--   1. Create a fresh RDS Postgres instance (engine 13+, any size)
--   2. Connect with a user that has CREATE privileges on the target database
--   3. Run this entire file in one transaction (it auto-wraps in BEGIN/COMMIT)
--   4. Uncomment the VERIFICATION block at the bottom and run to smoke-test
--
-- ── Idempotency ─────────────────────────────────────────────────────────────
--   This script is NOT idempotent — it fails if objects already exist.
--   For re-runs on the same DB, drop the schema first or use a fresh DB.
--   Intentional: catches accidental partial deploys that would leave orphans.
-- ============================================================================

BEGIN;

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 1 — ENUMs
-- ════════════════════════════════════════════════════════════════════════════

CREATE TYPE ticket_status AS ENUM (
  'AWAITING_EMPLOYEE_LIST', 'ASKED_CLIENT', 'PENDING_FINANCE',
  'READY_FOR_CHECKER', 'SENT_TO_CHECKER', 'PREPARING_FILES',
  'WITH_CHECKER', 'GROUP_MAPPING', 'DISBURSING',
  'CLOSING', 'COMPLETED', 'REJECTED'
);

CREATE TYPE ticket_scenario AS ENUM (
  'NORMAL', 'AMOUNT_MISMATCH', 'MISSING_APPROVAL'
);

CREATE TYPE ticket_risk_level AS ENUM ('LOW', 'MEDIUM', 'HIGH');

CREATE TYPE ticket_type AS ENUM ('SalaryToMA', 'SalaryToOTC');


-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 2 — Core ticket table (tickets_v2)
-- ────────────────────────────────────────────────────────────────────────────
-- Merges Binh's original design + all KAN-35 / KAN-36 / KAN-47 additions into
-- ONE CREATE TABLE (no later ALTER). Column order matches production Supabase.
-- UUID default uses gen_random_uuid() (Postgres 13+ built-in, no extension).
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE tickets_v2 (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number            VARCHAR(10) UNIQUE NOT NULL,  -- TKT-001 (auto-generated by trigger)
  company                  VARCHAR(100) NOT NULL DEFAULT 'Unknown Company',
  type                     ticket_type NOT NULL DEFAULT 'SalaryToMA',
  currency                 VARCHAR(3) NOT NULL DEFAULT 'MMK',
  scenario                 ticket_scenario NOT NULL DEFAULT 'NORMAL',
  status                   ticket_status NOT NULL DEFAULT 'AWAITING_EMPLOYEE_LIST',
  risk_level               ticket_risk_level NOT NULL DEFAULT 'LOW',

  -- ── Amounts (NUMERIC for financial precision) ──────────────────────────
  amount_requested         NUMERIC(18,2) NOT NULL DEFAULT 0,
  amount_on_bank_slip      NUMERIC(18,2) NOT NULL DEFAULT 0,
  amount_on_document       NUMERIC(18,2) NOT NULL DEFAULT 0,
  has_mismatch             BOOLEAN NOT NULL DEFAULT false,

  -- ── Approval matrix ────────────────────────────────────────────────────
  approval_matrix_complete BOOLEAN NOT NULL DEFAULT false,
  required_approvals       JSONB DEFAULT '[]'::jsonb,   -- [{role, name}]
  email_approvals          JSONB DEFAULT '[]'::jsonb,   -- [{role, name}]

  -- ── Finance workflow ───────────────────────────────────────────────────
  finance_status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',  -- PENDING/APPROVED/REJECTED
  finance_approved_by      TEXT,
  finance_approved_at      TIMESTAMPTZ,
  finance_notes            TEXT,

  -- ── Employee processing ────────────────────────────────────────────────
  prechecks_done           BOOLEAN NOT NULL DEFAULT false,
  prechecks_at             TIMESTAMPTZ,
  employee_data            JSONB DEFAULT '[]'::jsonb,    -- validated employee rows
  employee_total           NUMERIC(18,2) DEFAULT 0,
  total_employees          INT DEFAULT 0,
  invalid_msisdn_count     INT DEFAULT 0,
  names_cleaned_count      INT DEFAULT 0,
  employee_file_name       TEXT,
  reconciliation           JSONB,                        -- reconciliation check results

  -- ── Bank slip metadata ─────────────────────────────────────────────────
  bank_slip_filename       TEXT,
  bank_slip_type           VARCHAR(50),
  remark                   TEXT DEFAULT '',
  transaction_id           TEXT DEFAULT '',
  depositor_name           TEXT DEFAULT '',

  -- ── E-Money workflow state (drives dashboard deriveStatus() logic) ─────
  sent_to_checker          BOOLEAN NOT NULL DEFAULT false,
  checker_name             TEXT,
  checker_request          JSONB,     -- {corpWallet, dmmWallet, fee, batch, refNo}
  files_prepared           BOOLEAN NOT NULL DEFAULT false,
  mapping_in_progress      BOOLEAN NOT NULL DEFAULT false,
  mapping_complete         BOOLEAN NOT NULL DEFAULT false,
  disbursing               BOOLEAN NOT NULL DEFAULT false,
  monitor_results          JSONB,     -- {total, success, failed, paidAmount, failedAmount}
  closed                   BOOLEAN NOT NULL DEFAULT false,

  -- ── Source tracking ────────────────────────────────────────────────────
  n8n_source               BOOLEAN NOT NULL DEFAULT false,

  -- ── Timestamps ─────────────────────────────────────────────────────────
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- ── KAN-35 / KAN-36 email-side extraction fields (inlined from migration 13) ─
  payment_date             TEXT DEFAULT '',    -- client's pay day (e.g., "2026-04-20")
  payroll_period           TEXT DEFAULT '',    -- period salary covers (e.g., "March 2026")
  initiator_name           TEXT DEFAULT '',    -- who in client company is requesting
  purpose                  TEXT DEFAULT '',    -- why this disbursement
  cost_center              TEXT DEFAULT '',    -- accounting cost center (soft-gate)

  -- ── KAN-36 document-side mirror fields (inlined from migration 13) ─────
  doc_company_name         TEXT DEFAULT '',
  doc_payment_date         TEXT DEFAULT '',
  doc_initiator_name       TEXT DEFAULT '',
  doc_purpose              TEXT DEFAULT '',
  doc_cost_center          TEXT DEFAULT '',

  -- ── KAN-36 v11.4 Source Info (inlined from migration 14) ──────────────
  corporate_wallet         TEXT DEFAULT ''     -- e.g., "1200000289", "CHASE OPERATING - 123456789"
);


-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 3 — Child tables
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE ticket_emails (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id        UUID NOT NULL REFERENCES tickets_v2(id) ON DELETE CASCADE,
  source_email_id  TEXT NOT NULL,
  from_email       VARCHAR(255) DEFAULT '',
  to_email         VARCHAR(255) DEFAULT '',
  cc_emails        TEXT DEFAULT '',
  reply_to         TEXT DEFAULT '',
  email_date       TIMESTAMPTZ,
  message_id       TEXT DEFAULT '',
  thread_id        TEXT DEFAULT '',
  original_subject TEXT DEFAULT '',
  body_preview     TEXT DEFAULT '',
  email_body_full  TEXT DEFAULT '',
  has_attachments  BOOLEAN NOT NULL DEFAULT false,
  attachment_names JSONB DEFAULT '[]'::jsonb,
  attachment_count INT DEFAULT 0,
  n8n_source       BOOLEAN NOT NULL DEFAULT true,
  n8n_parsed_at    TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE ticket_attachments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id   UUID NOT NULL REFERENCES tickets_v2(id) ON DELETE CASCADE,
  file_name   VARCHAR(255) NOT NULL,
  mime_type   VARCHAR(255),          -- widened to 255 per migration 15 (XLSX MIME is 65 chars)
  storage_url TEXT,                  -- file path; storage backend is S3 on AWS, Supabase Storage on Supabase
  size_bytes  BIGINT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE ticket_vision_results (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id           UUID NOT NULL REFERENCES tickets_v2(id) ON DELETE CASCADE,
  attachment_id       UUID REFERENCES ticket_attachments(id),   -- nullable: legacy rows may not link
  vision_parsed       BOOLEAN NOT NULL DEFAULT false,
  vision_confidence   NUMERIC(5,4) DEFAULT 0,
  vision_status       VARCHAR(20) DEFAULT 'none',
  document_type       VARCHAR(50) DEFAULT '',
  document_signers    JSONB DEFAULT '[]'::jsonb,
  amount_on_document  NUMERIC(18,2) DEFAULT 0,
  depositor_name      TEXT DEFAULT '',
  remark              TEXT DEFAULT '',
  transaction_id      TEXT DEFAULT '',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE ticket_employee_extractions (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id           UUID NOT NULL REFERENCES tickets_v2(id) ON DELETE CASCADE,
  extracted_employees JSONB DEFAULT '[]'::jsonb,
  employee_count      INT DEFAULT 0,
  total_amount        NUMERIC(18,2) DEFAULT 0,
  confidence          NUMERIC(5,4) DEFAULT 0,
  status              VARCHAR(50) DEFAULT 'none',
  amount_mismatch     BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ────────────────────────────────────────────────────────────────────────────
-- activity_log — append-only audit trail
-- ────────────────────────────────────────────────────────────────────────────
-- FK references tickets_v2.ticket_number (TKT-xxx) for human readability in logs,
-- NOT the UUID id. This matches migration 11's FK fix.
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE activity_log (
  id         BIGSERIAL PRIMARY KEY,
  ticket_id  VARCHAR(10) REFERENCES tickets_v2(ticket_number) ON DELETE CASCADE,
  action     VARCHAR(20) NOT NULL,        -- CREATE, APPROVE, REJECT, UPDATE, etc.
  message    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 4 — Triggers
-- ════════════════════════════════════════════════════════════════════════════

-- Auto-update updated_at on every UPDATE to tickets_v2
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tickets_v2_updated_at
  BEFORE UPDATE ON tickets_v2
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- Auto-generate ticket_number (TKT-001, TKT-002, ...) when NULL/empty on INSERT
-- NOTE: this uses SELECT MAX + 1 which is NOT concurrency-safe under simultaneous
-- INSERT bursts. For AWS production under load, consider switching to a Postgres
-- sequence. For dashboard deploy evaluation this is sufficient.
CREATE OR REPLACE FUNCTION generate_ticket_number()
RETURNS TRIGGER AS $$
DECLARE
  max_num INT;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(ticket_number FROM 5) AS INT)), 0)
  INTO max_num
  FROM tickets_v2
  WHERE ticket_number LIKE 'TKT-%';

  NEW.ticket_number := 'TKT-' || LPAD(CAST(max_num + 1 AS TEXT), 3, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tickets_v2_auto_number
  BEFORE INSERT ON tickets_v2
  FOR EACH ROW
  WHEN (NEW.ticket_number IS NULL OR NEW.ticket_number = '')
  EXECUTE FUNCTION generate_ticket_number();


-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 5 — Indexes
-- ════════════════════════════════════════════════════════════════════════════

CREATE INDEX idx_ticket_emails_ticket_id        ON ticket_emails(ticket_id);
CREATE INDEX idx_ticket_attachments_ticket_id   ON ticket_attachments(ticket_id);
CREATE INDEX idx_ticket_vision_ticket_id        ON ticket_vision_results(ticket_id);
CREATE INDEX idx_ticket_vision_attachment_id    ON ticket_vision_results(attachment_id);
CREATE INDEX idx_ticket_extraction_ticket_id    ON ticket_employee_extractions(ticket_id);
CREATE INDEX idx_tickets_v2_status              ON tickets_v2(status);
CREATE INDEX idx_tickets_v2_ticket_number       ON tickets_v2(ticket_number);
CREATE INDEX idx_tickets_v2_created_at          ON tickets_v2(created_at DESC);
CREATE INDEX idx_activity_log_ticket_id         ON activity_log(ticket_id);
CREATE INDEX idx_activity_log_created_at        ON activity_log(created_at DESC);


-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 6 — Read-side VIEW (tickets_flat)
-- ────────────────────────────────────────────────────────────────────────────
-- Dashboard's primary query hits this view. It flattens one row per ticket with
-- the LATEST child rows (email, attachment, vision, employee extraction) joined
-- via LATERAL LIMIT 1. Column order matches production Supabase — dashboard JS
-- expects these column names and positions.
--
-- NOTE: For multi-attachment tickets (KAN-47), the view still shows only ONE
-- attachment/vision row (the latest). Dashboard Layer D queries ticket_attachments
-- directly for the full per-attachment detail.
-- ════════════════════════════════════════════════════════════════════════════

CREATE VIEW tickets_flat AS
SELECT
  -- ── Core (from tickets_v2) ──────────────────────────────────────────
  t.id,
  t.ticket_number,
  t.company, t.type::text, t.currency,
  t.scenario::text, t.status::text, t.risk_level::text,
  t.amount_requested, t.amount_on_bank_slip, t.amount_on_document,
  t.has_mismatch, t.approval_matrix_complete,
  t.required_approvals, t.email_approvals,
  t.finance_status, t.finance_approved_by, t.finance_approved_at, t.finance_notes,
  t.prechecks_done, t.prechecks_at,
  t.employee_data, t.employee_total, t.total_employees,
  t.invalid_msisdn_count, t.names_cleaned_count, t.employee_file_name,
  t.reconciliation,
  t.bank_slip_filename, t.bank_slip_type,
  t.remark, t.transaction_id, t.depositor_name,
  t.sent_to_checker, t.checker_name, t.checker_request, t.files_prepared,
  t.mapping_in_progress, t.mapping_complete, t.disbursing,
  t.monitor_results, t.closed,
  t.n8n_source,
  t.created_at, t.updated_at,

  -- ── Email (latest per ticket) ───────────────────────────────────────
  e.source_email_id, e.from_email, e.to_email, e.cc_emails,
  e.reply_to, e.email_date, e.message_id, e.thread_id,
  e.original_subject, e.body_preview, e.email_body_full,
  e.has_attachments, e.attachment_names, e.attachment_count,
  e.n8n_parsed_at,

  -- ── Attachment (latest per ticket) ──────────────────────────────────
  a.storage_url      AS attachment_url,
  a.mime_type        AS attachment_mime_type,
  a.file_name        AS attachment_file_name,

  -- ── Vision (latest per ticket) ──────────────────────────────────────
  v.vision_parsed, v.vision_confidence, v.vision_status,
  v.document_type, v.document_signers,

  -- ── Employee extraction (latest per ticket) ────────────────────────
  x.extracted_employees,
  x.employee_count   AS extracted_employee_count,
  x.confidence       AS employee_extraction_confidence,
  x.status           AS employee_extraction_status,
  x.total_amount     AS employee_total_extracted,
  x.amount_mismatch  AS employee_amount_mismatch,

  -- ── KAN-35 / KAN-36 fields (appended per production view order) ────
  t.payment_date, t.payroll_period,
  t.initiator_name, t.purpose, t.cost_center,
  t.doc_company_name, t.doc_payment_date,
  t.doc_initiator_name, t.doc_purpose, t.doc_cost_center,

  -- ── KAN-36 v11.4 Source Info ───────────────────────────────────────
  t.corporate_wallet

FROM tickets_v2 t
LEFT JOIN LATERAL (
  SELECT * FROM ticket_emails WHERE ticket_id = t.id ORDER BY created_at DESC LIMIT 1
) e ON true
LEFT JOIN LATERAL (
  SELECT * FROM ticket_attachments WHERE ticket_id = t.id ORDER BY created_at DESC LIMIT 1
) a ON true
LEFT JOIN LATERAL (
  SELECT * FROM ticket_vision_results WHERE ticket_id = t.id ORDER BY created_at DESC LIMIT 1
) v ON true
LEFT JOIN LATERAL (
  SELECT * FROM ticket_employee_extractions WHERE ticket_id = t.id ORDER BY created_at DESC LIMIT 1
) x ON true;


COMMIT;


-- ============================================================================
-- SECTION 7 — VERIFICATION BLOCK (uncomment and run to smoke-test the deploy)
-- ============================================================================
-- After a successful deploy, uncomment the block below and run it. Expected
-- results are noted in comments after each query.
-- ============================================================================

-- -- Check 1: All ENUMs created
-- SELECT typname FROM pg_type WHERE typcategory = 'E' ORDER BY typname;
-- -- Expected: 4 rows — ticket_risk_level, ticket_scenario, ticket_status, ticket_type

-- -- Check 2: All tables created
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
-- ORDER BY table_name;
-- -- Expected: 6 rows — activity_log, ticket_attachments, ticket_emails,
-- --           ticket_employee_extractions, ticket_vision_results, tickets_v2

-- -- Check 3: tickets_flat view exists with expected column count
-- SELECT count(*) AS tickets_flat_column_count
-- FROM information_schema.columns WHERE table_name = 'tickets_flat';
-- -- Expected: ~80 columns

-- -- Check 4: INSERT a test ticket — ticket_number should auto-generate as TKT-001
-- INSERT INTO tickets_v2 (company, amount_requested, currency)
-- VALUES ('AWS Smoke Test Co', 1000000.00, 'MMK');
-- SELECT ticket_number, company, amount_requested, status, created_at
-- FROM tickets_v2 ORDER BY created_at DESC LIMIT 1;
-- -- Expected: 1 row — ticket_number = 'TKT-001', status = 'AWAITING_EMPLOYEE_LIST'

-- -- Check 5: Activity log insert with FK to ticket_number
-- INSERT INTO activity_log (ticket_id, action, message)
-- VALUES ('TKT-001', 'CREATE', 'TKT-001 smoke-test created');
-- SELECT ticket_id, action, message FROM activity_log ORDER BY id DESC LIMIT 1;
-- -- Expected: 1 row matching what was inserted

-- -- Check 6: updated_at trigger fires on UPDATE
-- UPDATE tickets_v2 SET company = 'AWS Smoke Test Co (renamed)' WHERE ticket_number = 'TKT-001';
-- SELECT ticket_number, company, created_at, updated_at,
--        (updated_at > created_at) AS trigger_fired
-- FROM tickets_v2 WHERE ticket_number = 'TKT-001';
-- -- Expected: 1 row, trigger_fired = true

-- -- Check 7: tickets_flat returns the row
-- SELECT ticket_number, company, status, currency
-- FROM tickets_flat WHERE ticket_number = 'TKT-001';
-- -- Expected: 1 row

-- -- Cleanup after smoke test:
-- -- DELETE FROM activity_log WHERE ticket_id = 'TKT-001';
-- -- DELETE FROM tickets_v2 WHERE ticket_number = 'TKT-001';


-- ============================================================================
-- MIGRATION-NOTES — what still needs to move to AWS beyond this schema
-- ============================================================================
-- This schema is the FIRST STEP of the AWS migration. The following components
-- are NOT covered by this file and will be migrated in later phases:
--
-- 1. EMAIL INGESTION PIPELINE
--    Currently: n8n Cloud + Supabase email_queue + pg_net HTTP dispatch
--    AWS target: EventBridge + Lambda (or Step Functions), writing to a new
--                email_queue table (schema mirrors the Supabase version).
--    See: decisions/ADR-001_supabase_durable_queue.md and
--         decisions/ADR-002_pg_cron_plus_trigger_scheduling.md for current design.
--
-- 2. STORAGE
--    Currently: Supabase Storage private bucket "attachments", signed URLs on demand
--    AWS target: S3 bucket with presigned URLs. Dashboard changes: replace
--                supabase.storage.from(...).createSignedUrl() with AWS SDK
--                getSignedUrl() from s3. ticket_attachments.storage_url stores
--                the S3 key (same column, same type).
--
-- 3. AUTHENTICATION + ROW-LEVEL SECURITY
--    Currently: Supabase Auth JWT + RLS policies (auth.uid() based)
--    AWS target: Cognito (or IAM) + application-layer filters (or Postgres RLS
--                using custom claims via SET LOCAL). RLS policies deliberately
--                omitted from this file — add them after auth provider is chosen.
--
-- 4. DASHBOARD DEPLOYMENT
--    Currently: Vercel (Pro + Hobby)
--    AWS target: CloudFront + S3 static hosting, or Amplify Hosting. The
--                dashboard is single-file vanilla JS — any static host works.
--
-- 5. SECRETS
--    Currently: Vercel environment variables + Supabase Vault
--    AWS target: AWS Secrets Manager or Parameter Store.
--
-- Contact: DK Nguyen (DKNguyenTrustify@users.noreply.github.com)
-- Upstream docs: 03_build/decisions/ (ADR-001 through ADR-006)
-- ============================================================================
